ProjectJSONRPCValidate.view/Models/DefectModelVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectJSONRPCValidate.view.Models
{
    public class DefectModelVM
    {
        [Display(Name = "Defect No.")]
        public int DefectNo { get; set; }
        [Display(Name = "A/C No.")]
        public string ACNo { get; set; }
        [Display(Name = "Station")]
        public string Station { get; set; }
        [Display(Name = "Flight No.")]
        public string FlightNo { get; set; }
        [Display(Name = "Date/Time")]
        [DataType(DataType.Date)]
        public string Date { get; set; }
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Resolution")]
        public string Resolution { get; set; }

    }
}

ProjectJSONRPCValidate.view/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectJSONRPCValidate.view.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ProjectJSONRPCValidate.view/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectJSONRPCValidate.view.Models;
using ProjectJSONRPCValidate.wrapper.Core.Data.Defect;

namespace ProjectJSONRPCValidate.view.Pages
{
    public class IndexModel : PageModel
    {
        // Remote procedure call wrapper
        private readonly IDefectWrapper _defectWrapper;


        public IndexModel(IDefectWrapper defectWrapper)
        {
            _defectWrapper = defectWrapper;
        }

        public ResultMessage Message { get; set; }

        public class ResultMessage
        {
            public bool IsError { get; set; }
            public string Message { get; set; }

            public ResultMessage(string message, bool isError)
            {
                IsError = isError;
                Message = message;
            }
        }

        [BindProperty]
        public DefectModelVM Defect { get; set; } = new DefectModelVM();

        public List<DefectModelVM> DefectsList { get; set; }

        public async Task OnGetAsync()
        {
        }

        public async Task<IActionResult> OnPostSelectAsync()
        {
            // Check for valid defect number input
            if (Defect.DefectNo <= 0)
            {
                Message = new ResultMessage("Invalid defect number", true);

            }
            else
            {
                // Get the defect data
                var result = await _defectWrapper.GetByDefectNo(Defect.DefectNo);

                if (result.IsError)
                {
                    Message = new ResultMessage(result.Message, true);
                    Defect = new DefectModelVM { DefectNo = Defect.DefectNo };
                }
                else
                {
                    Message = new ResultMessage(result.Message, false);

                    Defect = new DefectModelVM
                    {
                        DefectNo = result.Defect.Defect,
                        ACNo = result.Defect.ACNo,
                        Station = result.Defect.Station,
                        FlightNo = result.Defect.Flight,
                        Date = DateTime.Parse(result.Defect.Reported_Date).ToString("yyyy-MM-dd"),
                        Description = result.Defect.Description,
                        Resolution = result.Defect.Resolution,
                    };
                }
            }

            return Page();
        }

        /// <summary>
        /// On insert
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnPostSaveAsync()
        {
            DefectModel defect = new DefectModel
            {
                Defect = Defect.DefectNo,
                ACNo = Defect.ACNo,
                Station = Defect.Station,
                Flight = Defect.FlightNo,
                Reported_Date = Defect.Date,
                Description = Defect.Description,
                Resolution = Defect.Resolution,

            };
            var response = await _defectWrapper.Add(defect);

            // Assign the view message
            Message = new ResultMessage(response.Message, response.IsError);

            return Page();
        }


        // Convert to JSON RPC IN THE VIEW WAY

        //public async Task<IActionResult> OnPostSaveAsync()
        //{
        //    DefectModel defect = new DefectModel
        //    {
        //        Defect = Defect.DefectNo,
        //        ACNo = Defect.ACNo,
        //        Station = Defect.Station,
        //        Flight = Defect.FlightNo,
        //        Reported_Date = Defect.Date,
        //        Description = Defect.Description,
        //        Resolution = Defect.Resolution,

        //    };

        //    // Create a model for json RPC
        //    var jsonRpcModel = new RPCRequestModel
        //    {
        //        Id = "1",
        //        Method = "insert",
        //        Params = JsonConvert.SerializeObject(defect) // Convert the defect data to json string
        //    };

        //    var response = await _rpc.Post(jsonRpcModel,"Defect");

        //    // Assign the view message
        //    Message = new ResultMessage(response.Message, response.IsError);
        //}
    }
}

ProjectJSONRPCValidate.view/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="row">
    <div class="col-md-8">
        <fieldset>
            <legend>Form</legend>
            <form method="post" class="border shadow p-3" >
                <div class="form-row">
                    <div class="col-auto">
                        <div class="form-group form-row">
                            <label asp-for="Defect.DefectNo" class="col-auto col-form-label"></label>
                            <div class="col-auto">
                                <input asp-for="Defect.DefectNo" class="form-control" value="@Model.Defect.DefectNo" />
                            </div>
                        </div>
                    </div>

                    <div class="col">
                        <button type="submit" asp-page-handler="select" class="btn btn-info">SELECT</button>
                    </div>

                    <div class="col">
                        <button type="submit" asp-page-handler="save" class="btn btn-success float-right">SAVE</button>
                    </div>

                </div>

                <div class="form-row">
                    <div class="col form-group">
                        <label asp-for="Defect.ACNo"></label>
                        <input asp-for="Defect.ACNo" class="form-control" value="@Model.Defect.ACNo" />
                    </div>
                    <div class="col form-group">
                        <label asp-for="Defect.Station"></label>
                        <input asp-for="Defect.Station" class="form-control" value="@Model.Defect.Station" />
                    </div>
                    <div class="col form-group">
                        <label asp-for="Defect.FlightNo"></label>
                        <input asp-for="Defect.FlightNo" class="form-control" value="@Model.Defect.FlightNo" />
                    </div>
                    <div class="col form-group">
                        <label asp-for="Defect.Date"></label>
                        <input asp-for="Defect.Date" class="form-control" value="@Model.Defect.Date" />
                    </div>
                </div>

                <div class="form-row">
                    <div class="col form-group">
                        @* Using asp-for For textarea wont fill out the value *@
                        <label asp-for="Defect.Description"></label>
                        <textarea id="@Html.IdFor(m => m.Defect.Description)" name="@Html.NameFor(m => m.Defect.Description)" class="form-control" rows="3">@Model.Defect.Description</textarea>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col form-group">
                        @* Using asp-for For textarea wont fill out the value *@
                        <label asp-for="Defect.Resolution"></label>
                        <textarea id="@Html.IdFor(m => m.Defect.Resolution)" name="@Html.NameFor(m => m.Defect.Resolution)" class="form-control" rows="3">@Model.Defect.Resolution</textarea>
                    </div>
                </div>
            </form>

            @if (Model.Message != null)
            {
                if (Model.Message.IsError)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        @Model.Message.Message
                    </div>
                }
                else
                {
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        @Model.Message.Message
                    </div>
                }

                Model.Message = null;
            }
        </fieldset>
    </div>
</div>

ProjectJSONRPCValidate.view/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectJSONRPCValidate.view</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ProjectJSONRPCValidate.view</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ProjectJSONRPCValidate.view
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>